from enum import Enum, unique


@unique
class ConstantesTexto(Enum):
    """Una clase que contiene la configuración para limpiar y preprocesar texto."""

    # Correcciones a errores comunes para algunas palabras
    correciones = (
        (" a credite", " acredite"),
        (" a dministradora", " administradora"),
        (" afp´s", " afp's"),
        (" aport e", " aporte"),
        (" a rtículo", " artículo"),
        (" artí culo", " artículo"),
        (" artíc ulo", " artículo"),
        (" banc a", " banca"),
        (" cobra nza", " cobranza"),
        (" cód igo", " código"),
        (" co mo", " como"),
        (" co n", " con"),
        (" con sta", " consta"),
        (" cuantia", " cuantía"),
        (" d e", " de"),
        (" d elegadas", " delegadas"),
        (" d emandado", " demandado"),
        (" dema ndado", " demandado"),
        (" docu mentos", " documentos"),
        (" electrón ica", " electrónica"),
        (" electróni ca", " electrónica"),
        (" e jecución", " ejecución"),
        (" eje cución", " ejecución"),
        (" fec ha", " fecha"),
        (" formal idad", " formalidad"),
        (" forza da", " forzada"),
        (" has ta", " hasta"),
        (" independ encia", " independencia"),
        (" in iciar", " iniciar"),
        (" judicatur a", " judicatura"),
        (" leg al", " legal"),
        (" liquidaci ón", " liquidación"),
        (" liquidació n", " liquidación"),
        (" liquidacione s", " liquidaciones"),
        (" l os", " los"),
        (" manusc rita", " manuscrita"),
        (" mi smo", " mismo"),
        (" mot ivo", " motivo"),
        (" movimiento s", " movimientos"),
        (" n ación", " nación"),
        (" n ormas", " normas"),
        (" no tificación", " notificación"),
        (" novie mbre", " noviembre"),
        (" o livo", " olivo"),
        (" olivo s", " olivos"),
        (" pret ensión", " pretensión"),
        (" previsi onal", " previsional"),
        (" pr evisionales", " previsionales"),
        (" previ sionales", " previsionales"),
        (" previs ionales", " previsionales"),
        (" probato rios", " probatorios"),
        (" r epresentación", " representación"),
        (" resp onsabilidad", " responsabilidad"),
        (" qu e", " que"),
        (" r ealizar", " realizar"),
        (" r esolución", " resolución"),
        (" so bre", " sobre"),
        (" tendra", " tendrá"),
        (" t exto", " texto"),
        (" tien e", " tiene"),
        (" traves", " través"),
        (" ú nico", " único"),
    )
